apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.image.tag }}
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_MONGODB_DBNAME
              value: {{ default "chegaai" .Values.environment.DATABASE_MONGODB_DBNAME | quote }}
            - name: DATABASE_MONGODB_URI
              value: {{ required "Mongodb URI is required" .Values.environment.DATABASE_MONGODB_URI | quote }}
            - name: AZURE_STORAGE_ACCOUNT_NAME
              value: {{ required "Storage acocunt name is required" .Values.environment.AZURE_STORAGE_ACCOUNT_NAME | quote }}
            - name: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
              value: {{ required "Storage access key is required" .Values.environment.AZURE_STORAGE_ACCOUNT_ACCESS_KEY | quote }}
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: {{ default "profiles" .Values.environment.AZURE_STORAGE_CONTAINER_NAME | quote }}
            - name: CLIENTS_GROUP_URL
              value: {{ default (tpl "http://ms-groups.{{.Release.Namespace}}.svc.cluster.local" .) .Values.environment.CLIENTS_GROUP_URL | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: registry-credentials
