# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: ms-profiles
env: production
maxReplicas: 10
cpuUsage: 60
memoryUsage: 80

image:
  registry: chegaai
  name: ms-profiles
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  portName: http

environment: {}

resources:
  requests:
    cpu: 250m
    memory: 128M
  limits:
    cpu: 500m
    memory: 256M
